kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
            stage ('id chk') {
                sh "id"
            }
        }
      type: JenkinsPipeline
